# Site settings
title: limerick
email: guods2015@gmail.com
description: "limerick's blog."
baseurl: ""
url: ""

# Build settings
markdown: redcarpet
permalink: pretty
exclude: [node_modules, scripts, bower_components]

sass:
  sass_dir: css
  style: :compressed

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
