# Site settings
title: limerick
email: guods2015@gmail.com
description: "limerick's blog."
baseurl: "/"
# url: "http://localhost:9999"
url: "http://limerickgds.github.io"

# Build settings
# markdown: redcarpet
permalink: pretty
exclude: [node_modules, bower_components, bower.json, Gemfile, Gemfile.lock, gulp-config.es6.js, gulpfile.es6.js, gulpfile.js, package.json, params.json]

#sass:
#  sass_dir: css
#  style: :compressed

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
