# Site settings
title: limerick
email: guods2015@gmail.com
description: "limerick's blog."
baseurl: "/"
url: "https://limerickgdsweb.com"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

permalink: pretty
exclude: [node_modules, bower_components, bower.json, Gemfile, Gemfile.lock, gulp-config.es6.js, gulpfile.es6.js, gulpfile.js, package.json, params.json]

# Google Analytics
ga_id: 'UA-92795568-1'         
ga_domain: limerickgdsweb.com

# Duoshuo settings
duoshuo_username: limerick

paginate: 10
paginate_path: "page:num"

#sass:
#  sass_dir: css
#  style: :compressed

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Gems
gems: 
  - jekyll-paginate
  - jekyll-sitemap