# Site settings
title: limerick
email: guods2015@gmail.com
description: "limerick's blog."
baseurl: "/"
# url: "http://localhost:9999"
url: "http://limerickgds.github.io"

# Build settings
highlight: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: false
  syntax_highlighter: rouge
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
permalink: pretty
exclude: [node_modules, bower_components, bower.json, Gemfile, Gemfile.lock, gulp-config.es6.js, gulpfile.es6.js, gulpfile.js, package.json, params.json]


paginate: 5
paginate_path: "page:num"

#sass:
#  sass_dir: css
#  style: :compressed

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Gems
gems: 
  - jekyll-paginate
  - jekyll-sitemap